//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Framework.Domain.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Status {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Status() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Framework.Domain.Resource.Status", typeof(Status).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The information entered is already registered.
        /// </summary>
        public static string AlreadyExist {
            get {
                return ResourceManager.GetString("AlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not possible to change the information.
        /// </summary>
        public static string CanNotCharge {
            get {
                return ResourceManager.GetString("CanNotCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete due to details.
        /// </summary>
        public static string CanNotDelete {
            get {
                return ResourceManager.GetString("CanNotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username  is duplicate.
        /// </summary>
        public static string DublicateUser {
            get {
                return ResourceManager.GetString("DublicateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while changing the password.
        /// </summary>
        public static string ExceptionInChangingUserPass {
            get {
                return ResourceManager.GetString("ExceptionInChangingUserPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to access this service.
        /// </summary>
        public static string Forbidden {
            get {
                return ResourceManager.GetString("Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid account.
        /// </summary>
        public static string InvalidAccount {
            get {
                return ResourceManager.GetString("InvalidAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The information entered is not valid.
        /// </summary>
        public static string InvalidModelState {
            get {
                return ResourceManager.GetString("InvalidModelState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information not found.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The previous password is incorrect.
        /// </summary>
        public static string OldPassIsNotCorrect {
            get {
                return ResourceManager.GetString("OldPassIsNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This serial has been registered more than 2 times..
        /// </summary>
        public static string SerialHasBeenRegisteredMoreThanTwo {
            get {
                return ResourceManager.GetString("SerialHasBeenRegisteredMoreThanTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The  serial number is invalid..
        /// </summary>
        public static string SerialNumberIsInvalid {
            get {
                return ResourceManager.GetString("SerialNumberIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product&apos;s serial does not exist in our database..
        /// </summary>
        public static string SerialNumberNotExists {
            get {
                return ResourceManager.GetString("SerialNumberNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should be older Than 18 years old..
        /// </summary>
        public static string ShouldBeOlderThan18 {
            get {
                return ResourceManager.GetString("ShouldBeOlderThan18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in user authentication.
        /// </summary>
        public static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unkown error.
        /// </summary>
        public static string UnkownError {
            get {
                return ResourceManager.GetString("UnkownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error in using database.
        /// </summary>
        public static string UseSqlServer {
            get {
                return ResourceManager.GetString("UseSqlServer", resourceCulture);
            }
        }
    }
}
